doctrine:
    dbal:
        host: 'data.pegasus.local'
        dbname: 'pegasus'
        user: 'kamailio'
        password: 'ironsecret'
        charset: 'utf8'
        server_version: '8.0'
        mapping_types:
            enum: string
            
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Pegasus/Gateway:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Pegasus\Gateway\Entity\'
